# -----------------------------------------------------------------------------
# MODELE DE CONFIGURATION - CONFIGURATION GENERIQUE (TEMPLATE)
# Copiez ce fichier sous le nom 'fredlab-secrets.values.yaml' pour le remplir localement.
# Ce fichier exemple EST tracé par Git. NE METTEZ AUCUNE VALEUR RÉELLE ICI.
# -----------------------------------------------------------------------------

# Mots de passe d'accès aux bases de données créées dans PostgreSQL
postgresql:
  admin:
    password: ""   # À REMPLIR : Mot de passe du superadmin 'postgres'
  keycloak:
    password: ""   # À REMPLIR : Utilisé par Keycloak pour sa database
  openfga:
    password: ""   # À REMPLIR : Utilisé par OpenFGA pour sa database
  temporal:
    password: ""   # À REMPLIR : Utilisé par Temporal pour sa database

# Configuration du serveur d'identité Keycloak
keycloak:
  admin:
    password: ""  # À REMPLIR : Mot de passe du compte 'admin' master initial
  
  # NOTE ÉQUIPE : Spécifier ici sous forme de commentaires ou de variables 
  # les emails des administrateurs nominatifs à provisionner sur cet environnement.

# Configuration de la sécurité de l'API OpenFGA (Fine-Grained Authorization)
openfga:
  auth:
    apiToken: ""  # À REMPLIR : Jeton partagé pour authentifier les clients de l'API Fred
