services:

  grafana:
    container_name: app-grafana
    restart: unless-stopped
    image: ${GRAFANA_IMAGE:-grafana/grafana:12.4.11}
    environment:
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/fred-logs.json
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-Azerty123_}
    networks:
      - app-network
    ports:
      - 0.0.0.0:${GRAFANA_PORT:-3002}:3000/tcp
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      - vol-grafana-data:/var/lib/grafana

volumes:
  vol-grafana-data:

networks:
  app-network:
    external: true
    name: fred-shared-network
