services:

  seaweedfs:
    container_name: app-seaweedfs
    image: chrislusf/seaweedfs:4.29
    environment:
      NO_PROXY: "*"
    command:
      - server
      - -ip=0.0.0.0
      - -dir=/data
      - -s3
      - -s3.config=/config/s3.json
      - -s3.port=8333
      - -master.port=9333
      - -volume.port=8080
      - -filer
      - -filer.port=8888
    networks:
      - app-network
    ports:
      - 0.0.0.0:9333:9333/tcp   # Master API
      - 0.0.0.0:8080:8080/tcp   # Volume API
      - 0.0.0.0:8888:8888/tcp   # Filer API
      - 0.0.0.0:8333:8333/tcp   # S3 API (compatible MinIO SDK)
    volumes:
      - vol-seaweedfs-data:/data
      - ./seaweedfs-config:/config:ro
    healthcheck:
      test: curl --fail http://localhost:9333/cluster/status
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
      start_interval: 2s

volumes:
  vol-seaweedfs-data:

networks:
  app-network:
    external: true
    name: fred-shared-network
