services:

  migrate:
    image: openfga/openfga:latest
    container_name: openfga-migrate
    command: migrate
    environment:
      OPENFGA_DATASTORE_ENGINE: postgres
      OPENFGA_DATASTORE_URI: postgres://${POSTGRES_OPENFGA_USER:-openfga}:${POSTGRES_OPENFGA_PASSWORD:-Azerty123_}@app-postgres:5432/${POSTGRES_OPENFGA_DBNAME:-openfga}?sslmode=disable
    networks:
      - app-network

  openfga:
    depends_on:
      migrate:
        condition: service_completed_successfully
    image: openfga/openfga:latest
    container_name: openfga
    environment:
      OPENFGA_DATASTORE_ENGINE: postgres
      OPENFGA_DATASTORE_URI: postgres://${POSTGRES_OPENFGA_USER:-openfga}:${POSTGRES_OPENFGA_PASSWORD:-Azerty123_}@app-postgres:5432/${POSTGRES_OPENFGA_DBNAME:-openfga}?sslmode=disable
      OPENFGA_LOG_FORMAT: json
      OPENFGA_HTTP_ADDR: 0.0.0.0:9080 # (changing from :8080 default to avoid conflict with Keycloak)
      OPENFGA_GRPC_ADDR: 0.0.0.0:9081
      OPENFGA_PLAYGROUND_ENABLED: "true"
      OPENFGA_PLAYGROUND_PORT: "3000"
      OPENFGA_METRICS_ENABLED: "true"
      OPENFGA_METRICS_ADDR: 0.0.0.0:2112
      OPENFGA_API_TOKEN: ${OPENFGA_API_TOKEN:-Azerty123_}
    command: run
    networks:
      - app-network
    ports:
      # Needed for the http server
      - "9080:9080"
      # Needed for the grpc server (if used)
      - "9081:9081"
      # Needed for the playground (Do not enable in prod!)
      - "3000:3000"

networks:
  app-network:
    external: true
    name: fred-shared-network
