{{- if .Values.ingress.enabled }}
{{- $managedCertificates := list .Values.ingress.managedCertificateName -}}
{{- if and .Values.temporal.enabled .Values.temporal.ui.enabled -}}
{{- $managedCertificates = append $managedCertificates .Values.temporal.ui.managedCertificateName -}}
{{- end -}}
{{- if .Values.fredFrontend.enabled -}}
{{- $managedCertificates = append $managedCertificates .Values.fredFrontend.managedCertificateName -}}
{{- end -}}
{{- range .Values.ingress.extraManagedCertificates -}}
{{- $managedCertificates = append $managedCertificates .name -}}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  labels:
    {{- include "fredlab-infra.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
    kubernetes.io/ingress.allow-http: {{ .Values.ingress.allowHttp | quote }}
    networking.gke.io/managed-certificates: {{ join "," ($managedCertificates | compact | uniq) | quote }}
    {{- if .Values.ingress.staticIpName }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.staticIpName | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.keycloakHost | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path | quote }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "fredlab-infra.keycloakName" . }}
                port:
                  name: http
    {{- if and .Values.temporal.enabled .Values.temporal.ui.enabled }}
    - host: {{ .Values.temporal.ui.hostname | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path | quote }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "fredlab-infra.temporalUiName" . }}
                port:
                  name: http
    {{- end }}
    {{- if .Values.fredFrontend.enabled }}
    - host: {{ .Values.fredFrontend.hostname | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path | quote }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "fredlab-infra.fredFrontendName" . }}
                port:
                  name: http
    {{- end }}
{{- end }}
