apiVersion: v1
kind: Service
metadata:
  name: {{ include "fredlab-infra.postgresName" . }}
  labels:
    {{- include "fredlab-infra.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - name: postgres
      port: {{ .Values.postgresql.service.port }}
      targetPort: postgres
  selector:
    {{- include "fredlab-infra.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
