apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  labels:
    {{- include "fred-stack.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.postgresSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seaweedfs-data
  labels:
    {{- include "fred-stack.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.seaweedfsSize }}
{{- if eq (include "fred-stack.clickhouseEnabled" .) "true" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-data
  labels:
    {{- include "fred-stack.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.clickhouseSize }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-data
  labels:
    {{- include "fred-stack.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.opensearchSize }}
{{- if eq (include "fred-stack.prometheusEnabled" .) "true" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  labels:
    {{- include "fred-stack.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.prometheusSize }}
{{- end }}
{{- if eq (include "fred-stack.grafanaEnabled" .) "true" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  labels:
    {{- include "fred-stack.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.grafanaSize }}
{{- end }}
