{
  "teams": [
    "northbridge",
    "thales",
    "swiftpost"
  ],
  "users": [
    {
      "username": "alice",
      "first_name": "Alice",
      "last_name": "Watson",
      "email": "alice@app.com",
      "password": "Azerty123_",
      "enabled": true,
      "app_roles": [
        "admin"
      ],
      "team_roles": {
        "manager": [
          "northbridge",
          "thales",
          "swiftpost"
        ]
      },
      "teams": [
        "northbridge",
        "thales",
        "swiftpost"
      ]
    },
    {
      "username": "bob",
      "first_name": "Bob",
      "last_name": "Rigg",
      "email": "bob@app.com",
      "password": "Azerty123_",
      "enabled": true,
      "app_roles": [
        "editor",
        "viewer"
      ],
      "teams": [
        "northbridge",
        "thales"
      ]
    },
    {
      "username": "phil",
      "first_name": "Phil",
      "last_name": "Woods",
      "email": "phil@app.com",
      "password": "Azerty123_",
      "enabled": true,
      "app_roles": [
        "viewer"
      ],
      "teams": [
        "northbridge",
        "swiftpost"
      ]
    },
    {
      "username": "zoe",
      "first_name": "Zoe",
      "last_name": "Martin",
      "email": "zoe@app.com",
      "password": "Azerty123_",
      "enabled": true,
      "app_roles": [
        "viewer"
      ],
      "teams": [
        "thales"
      ]
    },
    {
      "username": "liam",
      "first_name": "Liam",
      "last_name": "Dupont",
      "email": "liam@app.com",
      "password": "Azerty123_",
      "enabled": true,
      "app_roles": [
        "viewer"
      ],
      "teams": [
        "swiftpost"
      ]
    }
  ]
}
